=== CoriFletcher-USRA/gcn-starburst-schema/gcn/notices/icecube/GoldAndBronze.schema.json
{
  "$id": "https://gcn.nasa.gov/schema/gcn/notices/icecube/GoldAndBronze.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "IceCubeGoldAndBronzeTracks",
  "description": "IceCube Astrotrack Gold And Bronze track alert events",
  "properties": {
    "type": {
      "description": "Notice type Astrotrack Gold or Bronze",
      "type": "string"
    },
    "event": {
      "$ref": "/schema/gcn/notices/core/Event.schema.json"
    },
    "localization": {
      "$ref": "/schema/gcn/notices/core/Localization.schema.json"
    },
    "discovery_datetime": {
      "$ref": "/schema/gcn/notices/core/DateTime.schema.json"
    },
    "revision": {
      "description": "Revision number by IceCube",
      "type": "number"
    },
    "energy": {
      "description": "Most probable neutrino energy [TeV] that would have produced an event",
      "type": "number",
      "minimum": 0
    },
    "signalness": {
      "description": "Probability [dn] that this is an astrophysical signal relative to backgrounds",
      "type": "number",
      "minimum": 0
    },
    "far": {
      "description": "Rate of background events expected similar to alert event that would be seen by IceCube per year",
      "$ref": "/schema/gcn/notices/core/Statistics.schema.json"
    }
  },
  "required": [
    "type",
    "event",
    "localization",
    "discovery_datetime",
    "revision",
    "energy",
    "signalness",
    "far"
  ]
}

=== CoriFletcher-USRA/gcn-starburst-schema/gcn/notices/icecube/GoldAndBronze.example_update.json
{
  "$schema": "https://gcn.nasa.gov/schema/gcn/notices/icecube/GoldAndBronze.schema.json",
  "type": "IceCube Bronze Neutrino Track Alert",
  "event": {
    "event_name": ["IceCube-230416A"],
    "id": ["137840", "57034692"]
  },
  "localization": {
    "ra": 345.82,
    "dec": 9.01,
    "uncertainty_shape": "rectangle",
    "position_angle": 0,
    "semi_major": [-1.5, 1.4],
    "semi_minor": [-1.2, 1.3],
    "containment_probability": 0.9,
    "systematic_included": false,
    "healpix_url": "https://roc.icecube.wisc.edu/public/"
  },
  "discovery_datetime": {
    "trigger_time": "2023-04-16T05:22:26.150574"
  },
  "revision": 1,
  "energy": 127.29,
  "signalness": 0.34064,
  "far": {
    "far": 8.029e-8
  }
}
