=== CoriFletcher-USRA/gcn-starburst-schema/gcn/notices/swift/bat/guano/alert.schema.json
{
  "$id": "https://gcn.nasa.gov/schema/gcn/notices/swift/bat/guano/alert.schema.json",
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "alert_reporter": {
      "$ref": "/schema/gcn/notices/core/AlertReporter.schema.json"
    },
    "alert_info": {
      "$ref": "/schema/gcn/notices/core/AlertInfo.schema.json"
    },
    "event_info": {
      "$ref": "/schema/gcn/notices/core/EventInfo.schema.json"
    },
    "datetime": {
      "$ref": "/schema/gcn/notices/core/DateTime.schema.json"
    },
    "localization": {
      "$ref": "/schema/gcn/notices/core/Localization.schema.json"
    },
    "statistics": {
      "$ref": "/schema/gcn/notices/core/Statistics.schema.json"
    },
    "identifiers": {
      "$ref": "/schema/gcn/notices/core/Identifiers.schema.json",
      "description": "data archive only"
    }
  },
  "required": [
    "alert_reporter",
    "alert_info",
    "event_info",
    "datetime",
    "identifiers"
  ]
}

=== CoriFletcher-USRA/gcn-starburst-schema/gcn/notices/swift/bat/guano/alert.example.json
{
  "$schema": "https://gcn.nasa.gov/schema/gcn/notices/swift/bat/guano/alert.schema.json",
  "alert_reporter": {
    "mission": "Swift",
    "instrument": "BAT-GUANO",
    "record_number": 1
  },
  "alert_info": {
    "alert_datetime": "[UTC, ISO 8601]",
    "alert_tense": "current",
    "alert_type": "initial"
  },
  "event_info": {
    "event_id": "name"
  },
  "datetime": {
    "trigger_time": "Time of the trigger [ISO 8601]"
  },
  "statistics": {
    "rate_snr": 7.5,
    "rate_duration": 0.256,
    "rate_energy_range": {
      "energy_low": 15,
      "energy_high": 350
    },
    "classification": "GRB"
  },
  "identifiers": {
    "data_archive_page": "https://swift.gsfc.nasa.gov/archive/"
  }
}
